name: CI

on:
  push:
    branches:
    - develop
    - feature/*
    - hotfix/*

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Get poetry
        run: |
          pip install poetry==1.1.5
      - name: install project dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install
      - name: Check code formatting
        run: |
          black --check ./itsml/ --exclude __init__.py --verbose
      - name: Check import orders
        run: |
          isort --check ./itsml/ --skip __init__.py --gitignore --dont-follow-links --verbose
      - name: Linter
        run: |
          pylama ./itsml/ ./tests/
      - name: Run tests
        run: |
          pytest ./tests/ --verbose --color=yes --code-highlight=yes
